# Generated by Django 2.2.7 on 2019-11-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20191116_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_Name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
